name: Build & Release Desktop App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    # Grant permissions to the job to create a release
    permissions:
      contents: write

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          # Set Node.js version to 20, as required by dependencies
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build and release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token is automatically provided to the action
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The action will create a draft release and upload the assets
          release: true